In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style(style="whitegrid")
plt.rcParams["figure.figsize"] = (8, 4)
pd.set_option("display.max_columns", None)

print("Libraries Ready")

Libraries Ready

In [2]:
purchases = pd.read_csv("customer_purchases.csv")
feedback = pd.read_csv("customer_feedback.csv")

display(purchases.head())
display(feedback.head())

   CustomerID  Gender AgeGroup Region ProductCategory  Quantity  Sales
0           1    Male    46-60  North         Grocery         2     84
1           2  Female    26-35  North        Clothing         4    352
2           3  Female    18-25  North        Clothing         3    207
3           4    Male    26-35   West         Grocery         5    125
4           5    Male    18-25   East        Clothing         1     22

   FeedbackID Channel Region  Satisfaction
0           1  Online   West       Neutral
1           2  Online   East     Satisfied
2           3  Online  North  Dissatisfied
3           4  Online   West       Neutral
4           5  Online   East     Satisfied